// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetUserEmailUsecase is an autogenerated mock type for the GetUserEmailUsecase type
type GetUserEmailUsecase struct {
	mock.Mock
}

// BeforeLogin provides a mock function with given fields: nonce
func (_m *GetUserEmailUsecase) BeforeLogin(nonce string) (string, error) {
	ret := _m.Called(nonce)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(nonce)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nonce)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmail provides a mock function with given fields: code, nonce
func (_m *GetUserEmailUsecase) GetEmail(code string, nonce string) (string, error) {
	ret := _m.Called(code, nonce)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(code, nonce)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(code, nonce)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
