// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "atwell/domain"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// TweetRepository is an autogenerated mock type for the TweetRepository type
type TweetRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: comment
func (_m *TweetRepository) Create(comment string) (domain.Tweet, error) {
	ret := _m.Called(comment)

	var r0 domain.Tweet
	if rf, ok := ret.Get(0).(func(string) domain.Tweet); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Get(0).(domain.Tweet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *TweetRepository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: user, from, to
func (_m *TweetRepository) Get(user domain.User, from time.Time, to time.Time) ([]domain.Tweet, error) {
	ret := _m.Called(user, from, to)

	var r0 []domain.Tweet
	if rf, ok := ret.Get(0).(func(domain.User, time.Time, time.Time) []domain.Tweet); ok {
		r0 = rf(user, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tweet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.User, time.Time, time.Time) error); ok {
		r1 = rf(user, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
